name: TEXTBOOK
fixed: false
contentDir: OEBPS
coverImage:
  - src: '../images/cover.jpg'
    alt: 'cover image'
title:
  - type: main
    text: Textbook
  - type: subtitle
    text: Subtitle
creator:
  - role: author
    text: Lorem Creator
  - role: editor
    text: Ipsum Creator
identifier:
  - scheme: URN
    text: urn:uuidLOREMIPSUM
publisher: Publisher
rights: © 2019 Publisher
date: '2018-08-22T01:47:08-04:00'
language: en-US
ibooks:
  version: 1.3.4
pages:
  page01:
    toc: 'First Page'
    properties: ['scripted']
